#!/bin/bash

#SBATCH --time=40:00:00
#SBATCH --ntasks=20

ulimit -c 0 
export PATH="/scratch/td7g11/julia/julia-1.1.0/bin/:${PATH}"

cd $HOME/routing_analysis

julia -p 20  scripts/run_discretization_study.jl 90
julia -p 20  scripts/run_discretization_study.jl 80
julia -p 20  scripts/run_discretization_study.jl 70
julia -p 20  scripts/run_discretization_study.jl 60
julia -p 20  scripts/run_discretization_study.jl 50
julia -p 20  scripts/run_discretization_study.jl 40
julia -p 20  scripts/run_discretization_study.jl 30
julia -p 20  scripts/run_discretization_study.jl 20
julia -p 20  scripts/run_discretization_study.jl 10
