#!/bin/bash

#SBATCH --time=40:00:00
#SBATCH --ntasks=5

ulimit -c 0
export PATH="/scratch/td7g11/julia/julia-1.1.0/bin/:${PATH}"

cd $HOME/routing_analysis

julia -p 5 scripts/compare_seafaring_tech.jl $SLURM_ARRAY_TASK_ID