#!/bin/bash

#SBATCH --time=40:00:00
#SBATCH --ntasks=10

ulimit -c 0 
export PATH="/scratch/td7g11/julia/julia-1.1.0/bin/:${PATH}"

cd $HOME/routing_analysis

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
fname=total_simulations.$current_time.txt

julia -p 10  scripts/run_ensemble_route.jl $SLURM_ARRAY_TASK_ID
